# .prettierrc.yml
# see: https://prettier.io/docs/en/options.html
tabWidth: 4
useTabs: false
printWidth: 120
semi: true
singleQuote: true
trailingComma: es5
bracketSpacing: true
arrowParens: always
proseWrap: always
